# Non Graded Challenge 6

_Non-Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program khususnya pada konsep Linear Algebra._

---

## Assignment Instructions

Apakah $\begin{bmatrix}1 \\3\end{bmatrix}$ adalah eigenvector dari $\begin{bmatrix}1 & -1\\6 &-4 \end{bmatrix}$? Jika iya, berapakah eigenvalue-nya?

## Assignment Submission

- Simpan assignment pada sesi ini dengan nama `h8dsft_Linear_Algebra3`.
- Push Assigment yang telah kalian buat ke akun Github kalian masing-masing.

## Assignment Objectives

Non-Graded Assignment ini dibuat guna mengevaluasi konsep Linear Algebra sebagai berikut:

- Memahami konsep eigenvalue dan eigenvector
- Dapat mencari eigenvalue dan eigenvector

#### Library yang digunakan

In [1]:
import numpy as np
from numpy.linalg import eig

In [6]:
#Melakukan declare vector
U = np.array([[1],[3]])
A = np.array([[1,-1],
              [6,-4]])

print("U = \n", U)
print("         ")
print("A = \n", A)

U = 
 [[1]
 [3]]
         
A = 
 [[ 1 -1]
 [ 6 -4]]


In [8]:
values, vector = eig(A)
print (values)
print (vector)
values

[-1. -2.]
[[0.4472136  0.31622777]
 [0.89442719 0.9486833 ]]


array([-1., -2.])

In [9]:
# transformasi T : U -> W
W = A.dot(U)
print(W)

[[-2]
 [-6]]


In [10]:
#Eigen Value 1
coba = values[0]*u
print(coba)

[[-1.]
 [-3.]]


In [11]:
T = np.array([[5,1],
              [3,3]])
v = np.array([[1],
              [1]])
T
v

array([[1],
       [1]])

In [12]:
x, y = eig(T)
print(x)

print(y)

[6. 2.]
[[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]


In [13]:
#hasil dari w adalah
result = T.dot(v)
result

array([[6],
       [6]])

In [14]:
6*v

array([[6],
       [6]])